services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf-simple:latest
    container_name: bentopdf
    ports:
      - "${MODULAB_PUBLISH_IP:-0.0.0.0}:8084:8080"
    environment:
      DISABLE_IPV6: ${DISABLE_IPV6:-false}
    restart: unless-stopped
