services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"
    network_mode: "bridge"
    ports:
      - "8096:8096"
      - "8920:8920"
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/cache:/cache
      - ./media:/media
    env_file:
      - .env.jellyfin
    environment:
      - TZ=${TZ:-Etc/UTC}
    restart: unless-stopped
